### PR TITLE
adding event for SES

### PR DESCRIPTION
**Pull request by jeromevdl**
*Issue #, if available:*

*Description of changes:* Adding the Event for SES.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jeromevdl** [comment]
Actually, it does not work because of the "Records" (upper case R), will need a mixin...

**Comment by jeromevdl** [comment]
Added the mixin to serialization module but need to be ported to Lambda Runtime...

**Comment by mr-smithers-excellent** [comment]
@msailes - would love to see an `SESEvent` added to the library. Currently using custom objects to deserialize. Any chance you can give this PR another look?

**Comment by msailes** [comment]
Hi Sean, 

Thanks for the feedback. We're in the run up to the next major version [v4](https://github.com/aws/aws-lambda-java-libs/issues/282). This will make adding events like this one a lot easier.

Thanks for your patience,

Mark

**Comment by msailes** [comment]
Closing, superseded by https://github.com/aws/aws-lambda-java-libs/pull/345

**Pull request closed without merging**
