### PR TITLE
Support for Multi-Value Headers and Query String Parameters

### PR DESCRIPTION
**Pull request by medinarrior**
*Issue #60*

*Description of changes:* Support for multi-value headers and query string parameters in the Input of a Lambda Function for Proxy Integration. Output remains without change.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tphokas** [comment]
Thank you for the pull request. I've tested it and all seems to be fine.
**Testing done:**
- Checked out the PR
- Created a Java AWS Lambda function with ```APIGatewayProxyRequestEvent``` as input
- Successfully printed the added parameters

**Comment by medinarrior** [comment]
Great! Is there any plan to release a new version soon?

**Comment by tphokas** [comment]
We just did :). Check [here](https://repo.maven.apache.org/maven2/com/amazonaws/aws-lambda-java-events/2.2.3/)

**Comment by siddharthTyagi** [comment]
What's the right way to set multi value headers via proxy response event?

**Pull request merged**
