### PR TITLE
Add IoTCustomAuthorizerEvent and Response

### PR DESCRIPTION
**Pull request by fkhantsi**
*Description of changes:*
Adding IoT Custom Authorizer Event and Response to events library

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by msailes** [comment]
Could you add a javadoc link to the documentation for the event?

**Comment by fkhantsi** [comment]
Done

**Review by msailes — APPROVED** [review]
LGTM

**Review by andclt — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
